title: Nourhan Hamda - Software Engineer
description: 5+ years experience in PHP/Laravel/.NET, E-commerce & API Integration, and Cloud Architecture
theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
