name: Generate Resume PDF
on:
  push:
    paths:
      - 'index.html'
  workflow_dispatch:  # Allow manual triggering
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      
      # Use wkhtmltopdf for most reliable HTML to PDF conversion
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf xvfb
          
      # Install proper fonts to ensure consistent rendering
      - name: Install fonts
        run: |
          sudo apt-get install -y fonts-liberation fonts-dejavu fonts-noto
      
      # Generate PDF using wkhtmltopdf with Xvfb (virtual display)
      - name: Generate PDF
        run: |
          xvfb-run wkhtmltopdf \
            --enable-local-file-access \
            --page-size A4 \
            --margin-top 15mm \
            --margin-right 15mm \
            --margin-bottom 15mm \
            --margin-left 15mm \
            --encoding UTF-8 \
            --no-outline \
            index.html Nourhan_Hamda_Resume.pdf
      
      # Check that PDF was created successfully
      - name: Verify PDF
        run: |
          ls -la Nourhan_Hamda_Resume.pdf
          file Nourhan_Hamda_Resume.pdf
      
      # Commit the PDF to the repository
      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin ${{ github.ref_name }}  # Sync first!
          git add Nourhan_Hamda_Resume.pdf
          git commit -m "chore: Update Generated Resume PDF - $(date '+%Y-%m-%d') [skip ci]" || echo "No changes to commit"
          git push origin ${{ github.ref_name }}
